# --- Database ---
datasources:
  postgres:
    url: ${KESTRA_PG_URL}
    driverClassName: org.postgresql.Driver
    username: ${KESTRA_PG_USER}
    password: ${KESTRA_PG_PASSWORD}

# --- Kestra core ---
kestra:
  queue:
    type: postgres
  repository:
    type: postgres

  storage:
    type: local
    local:
      # use a writable path inside the image
      basePath: /app/storage

  url: ${PUBLIC_URL:`http://localhost:8080/`}

  server:
    basicAuth:
      username: ${KESTRA_USERNAME:`[email protected]`}
      password: ${KESTRA_PASSWORD:`change-me-please`}

# --- Health/metrics ---
endpoints:
  all:
    port: 8081
