# --- Database (PostgreSQL on Railway) ---
datasources:
  postgres:
    url: ${KESTRA_PG_URL}
    driverClassName: org.postgresql.Driver
    username: ${KESTRA_PG_USER}
    password: ${KESTRA_PG_PASSWORD}

# --- Kestra core ---
kestra:
  queue:
    type: postgres
  repository:
    type: postgres

  storage:
    type: local
    local:
      basePath: /data/storage

  url: ${PUBLIC_URL:`http://localhost:8080/`}

  # Identity management (new auth system)
  identity:
    type: database
    bootstrap:
      email: ${ADMIN_EMAIL:`[email protected]`}
      password: ${ADMIN_PASSWORD:`change-me-please`}

# --- Health/metrics ---
endpoints:
  all:
    port: 8081
